---
title: "Seabirds vs nutrients"
author: "CEB"
date: '2024-09-04'
output: html_document
---

#load packages
```{r}
#for everything:
library(tidyverse)

#for bayesian analysis:
library(brms)
library(tidybayes)

#for partialize:
library(jtools)

#for combining plots:
library(cowplot)


```


###set plot theme
```{r}
theme_casey<-
  theme_bw()+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        text = element_text(size = 14, family = "Arial"),
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA)
        )

theme_set(theme_casey) 
  
```


#load data
```{r}
#from data prep file, already combined,but need to add island size based on updated DAG:

leaf_n15_dat<-read.csv("../data/seychelles_leaf_n15_dat.csv")%>%
  select(-X)%>%
   mutate(island_size = case_when(Island == "Aride"~71,
                                 Island == "Cousine"~26,
                                 Island == "Felicite"~268,
                                 Island == "Fregate"~206))

turf_n15_dat<- read.csv("../data/seychelles_turf_n15_dat.csv")%>%
  select(-X)%>%
   mutate(island_size = case_when(Island == "Aride"~71,
                                 Island == "Cousine"~26,
                                 Island == "Felicite"~268,
                                 Island == "Fregate"~206))




```



##Bayesian analysis based on DAGs - Hypothesis 1: effect of seabirds on leaf n15
```{r}

#add column for log and centered data:----
leaf_n15_dat_wlog<-
  leaf_n15_dat%>%
  mutate(log_seabird = log(seabird.biomass.total+1),
         log_n15 = log(N15))%>%
  mutate(island_size_c = base::scale(island_size, center = TRUE, scale = TRUE),
         log_seabird_c = base::scale(log_seabird, center = TRUE, scale = FALSE))
leaf_n15_dat_wlog


#brms models------
#see previous file for other options/build-up
#also compared uninformative versus weakly informative prior, results nearly identical so can just use uninformative

#log-log model, uninformative prior: 
sb_leaf_n15_brms<-
  brm(
 log_n15~log_seabird_c + (1|Island),
  data = leaf_n15_dat_wlog, 
  iter = 3000, warmup = 1000, chains = 4, cores = 4,
   control = list(adapt_delta = 0.999, max_treedepth = 15), 
      file = "../outputs/brms/sb_leaf_n15_brms") #all good
print(sb_leaf_n15_brms)


# do some checks:
pp_check(sb_leaf_n15_brms) #looks great
plot(sb_leaf_n15_brms) #looks great

plot(hypothesis(sb_leaf_n15_brms, "log_seabird_c>0"))
hypothesis(sb_leaf_n15_brms, "log_seabird_c>0")
#looks great:
#hypothesis                est      error     lower     upper       evidence ratio        posterior probability
#(log_seabird_cs) > 0	    0.17	0.03	0.13	0.22	Inf	1	*


#extract some values:------
sb_leaf_n15_brms %>%
  spread_draws(b_log_seabird_c) %>%
  median_hdi(b_log_seabird_c)
#b_log_seabird      lower       upper     width   point     interval
#0.174379	      0.1164461	0.2314263		0.95	    median  	hdi


#extract some values, back transformed (A doubling of seabird biomass is associated with a change in median of n15 by a factor of (2^B). - becauase log-log)
sb_leaf_n15_brms %>%
  spread_draws(b_log_seabird_c) %>%
  median_hdi((2^b_log_seabird_c))
#log(2^b_log_seabird)      lower       upper        width   point     interval
#1.128479             	1.083846	1.173859			    .95       median      hdi


###based on updated DAG, need to add island size-------
sb_leaf_n15_size_brms<-
  brm(
 log_n15~log_seabird_c + island_size_c + (1|Island),
  data = leaf_n15_dat_wlog, 
  iter = 3000, warmup = 1000, chains = 4, cores = 4,
   control = list(adapt_delta = 0.999, max_treedepth = 15), 
      file = "../outputs/brms/sb_leaf_n15_size_brms") #all good
print(sb_leaf_n15_size_brms)


# do some checks:
pp_check(sb_leaf_n15_size_brms) #looks great
plot(sb_leaf_n15_size_brms) #looks great

plot(hypothesis(sb_leaf_n15_size_brms, "log_seabird_c>0"))
hypothesis(sb_leaf_n15_size_brms, "log_seabird_c>0")
#looks great:
#hypothesis                est      error     lower     upper       evidence ratio        posterior probability
#(log_seabird_cs) > 0	     0.16	0.03	0.11	0.21	Inf	1	*
#nearly identical to above***

#extract some values:------
sb_leaf_n15_size_brms %>%
  spread_draws(b_log_seabird_c) %>%
  median_hdi(b_log_seabird_c)
#0.1611862	0.09869027	0.2195903	

#back transformed (A doubling of seabird biomass is associated with a change in median of n15 by a factor of (2^B). - becauase log-log)
sb_leaf_n15_size_brms %>%
  spread_draws(b_log_seabird_c) %>%
  median_hdi((2^b_log_seabird_c))
#log(2^b_log_seabird)      lower       upper        width   point     interval
#1.118206	1.069592	1.163357				    .95       median      hdi
#nearly identical to above**

```


##Bayesian analysis based on DAGs - Hypothesis 2: effect of seabirds on turf n15
```{r}
#add column for log and centered/scaled data:----
turf_n15_dat_wlog<-
  turf_n15_dat%>%
  mutate(log_seabird = log(seabird.biomass.total+1),
         log_n15 = log(N15))%>%
  mutate(island_size_c = base::scale(island_size, center = TRUE, scale = TRUE),
         log_seabird_c = base::scale(log_seabird, center = TRUE, scale = FALSE))
turf_n15_dat_wlog


#brms models------
#see previous file for other options/build-up
#also compared uninformative versus weakly informative prior, results nearly identical so can just use uninformative

#log-log model, uninformative prior: 
sb_turf_n15_brms<-
  brm(
 log_n15~log_seabird_c + (1|Island),
  data = turf_n15_dat_wlog, 
  iter = 3000, warmup = 1000, chains = 4, cores = 4,
   control = list(adapt_delta = 0.999, max_treedepth = 15), 
      file = "../outputs/brms/sb_turf_n15_brms") 
print(sb_turf_n15_brms)


# do some checks:
pp_check(sb_turf_n15_brms) #looks great
plot(sb_turf_n15_brms) #looks great

plot(hypothesis(sb_turf_n15_brms, "log_seabird_c>0"))
hypothesis(sb_turf_n15_brms, "log_seabird_c>0")
#looks great:
#hypothesis           est      error     lower     upper       evidence ratio        posterior probability
#(log_seabird_c) > 0	0.06      	0.04    	0	      0.13        	16.24	              0.94	


#extract some values:------
sb_turf_n15_brms %>%
  spread_draws(b_log_seabird_c) %>%
  median_hdi(b_log_seabird_c)
#b_log_seabird      lower       upper     width   point     interval
#0.06205126     	-0.01908915	0.1454426			  0.95	median	hdi


#extract some values, back transformed (A doubling of seabird biomass is associated with a change in median of n15 by a factor of (2^B). - because log-log)

sb_turf_n15_brms %>%
  spread_draws(b_log_seabird_c) %>%
  median_hdi((2^b_log_seabird_c))
#log(2^b_log_seabird)      lower       upper        width   point     interval
#1.043949	                  0.9864829	1.105614			  0.95	median	hdi  




###based on updated DAG, need to add island size-------
sb_turf_n15_size_brms<-
  brm(
 log_n15~log_seabird_c + island_size_c + (1|Island),
  data = turf_n15_dat_wlog, 
  iter = 3000, warmup = 1000, chains = 4, cores = 4,
   control = list(adapt_delta = 0.999, max_treedepth = 15), 
      file = "../outputs/brms/sb_turf_n15_size_brms") #all good
print(sb_turf_n15_size_brms)


# do some checks:
pp_check(sb_turf_n15_size_brms) #looks great
plot(sb_turf_n15_size_brms) #looks great

plot(hypothesis(sb_turf_n15_size_brms, "log_seabird_c>0"))
hypothesis(sb_turf_n15_size_brms, "log_seabird_c>0")
#looks great:
#hypothesis                est      error     lower     upper       evidence ratio        posterior probability
#(log_seabird_cs) > 0	   0.08	0.05	0	0.16	16.54	0.94	
#nearly identical to above*

#extract some values:------
sb_turf_n15_size_brms %>%
  spread_draws(b_log_seabird_c) %>%
  median_hdi(b_log_seabird_c)


#back transformed (A doubling of seabird biomass is associated with a change in median of n15 by a factor of (2^B). - becauase log-log)
sb_turf_n15_size_brms %>%
  spread_draws(b_log_seabird_c) %>%
  median_hdi((2^b_log_seabird_c))
#log(2^b_log_seabird)      lower       upper        width   point     interval
#1.056522	          0.9789206	        1.126548	    0.95       median      hdi
#nearly identical to above*

```


#model plots----
```{r}

#conditional effects, with partial residuals-----
#first for turf-----
#effect line:
me_turf_sb<-conditional_effects(sb_turf_n15_brms, prob = .75, effects = 'log_seabird_c', plot = FALSE)[[1]]

#extract partialized residuals
p_turf_sb<-partialize(sb_turf_n15_brms, vars= "log_seabird_c",  data = turf_n15_dat_wlog)

#get data for un-centering:
mean(turf_n15_dat_wlog$log_seabird, na.rm=TRUE) #3.218641

me_turf_seabird_unscale<-
  me_turf_sb%>%
  mutate(log_seabird = (log_seabird_c + 3.218641)) # + mean


#no jitter:
turf_part_plot<-
p_turf_sb %>%
  ggplot(aes(x = log_seabird, y = exp(log_n15))) +
     geom_point(color = "#009E73", fill = "#009E73", alpha = 0.4, size = 3) + #, size = .8
    geom_ribbon(data = me_turf_seabird_unscale, aes(ymin = exp(lower__), ymax=exp(upper__)), alpha = .2, fill = "#009E73")+
    geom_line(data = me_turf_seabird_unscale, aes(x = log_seabird, y = exp(estimate__)), lwd = 1.2, colour = "#009E73") +
  xlab(bquote(Seabird~biomass~(kg~ha^-1)))+ #re-label x axis rather than leaving on log scale
  ylab(expression(paste("Turf ", delta^15, "N"))) + 
  scale_x_continuous(labels = c(1, 10, 100), breaks = c(log(2),  log(11), log(101)))+ #because of +1 in log-transformation, here log(1) = 0*** and subtract 1 from all labels
  theme_bw()+
    guides(size = "none", colour = "none",  fill = guide_legend(title="Confidence level")) + 
    theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
    #            text = element_text(size = 24),
        legend.position='none')
turf_part_plot


#raw effect size posterior distribution plot:
turf_post_plot<-
sb_turf_n15_brms %>%
  spread_draws(b_log_seabird_c) %>%
 # mutate(exp_b=exp(b_treatment_bNo_rats))%>%
  ggplot(aes(y = 0, x = b_log_seabird_c, fill = "#009E73")) +
  stat_halfeye(point_interval=median_hdi, .width=c(.95, .75), fatten_point = 2, slab_alpha = 0.6) +
  scale_fill_manual(values = alpha(c("#009E73"),0.3))+
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw() + 
  xlab("")+
  ylab("")+
 # scale_x_continuous(limits=c(-1.3, 2), breaks=seq(-1, 2,1))+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = "none",  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
      #  text=element_text(size=16,  family="sans"),
          axis.text.y = element_blank(),
        axis.ticks.y = element_blank())
turf_post_plot


#now for leaves-----
#effect line:
me_leaf_sb<-conditional_effects(sb_leaf_n15_brms, prob = .75, effects = 'log_seabird_c', plot = FALSE)[[1]]

#extract partialized residuals
p_leaf_sb<-partialize(sb_leaf_n15_brms, vars= "log_seabird_c",  data = leaf_n15_dat_wlog)

#get data for un-scaling and centering:
mean(leaf_n15_dat_wlog$log_seabird, na.rm=TRUE) #3.125881

me_leaf_seabird_unscale<-
  me_leaf_sb%>%
  mutate(log_seabird = log_seabird_c + 3.125881 ) # + mean


leaf_part_plot<-
p_leaf_sb %>%
  ggplot(aes(x = log_seabird, y = exp(log_n15))) +
     geom_point(color = "#009E73", fill = "#009E73", alpha = 0.4, size = 3) + #, size = .8
    geom_ribbon(data = me_leaf_seabird_unscale, aes(ymin = exp(lower__), ymax=exp(upper__)), alpha = .2, fill = "#009E73")+
    geom_line(data = me_leaf_seabird_unscale, aes(x = log_seabird, y = exp(estimate__)), lwd = 1.2, colour = "#009E73") + #scale line thickness to PP - >0.9 = 1.2 (original thickness)
 # xlab("Seabird biomass (log kg-1 ha-1)")+
ylab(expression(paste("Leaf ", delta^15, "N"))) + 
  xlab(bquote(Seabird~biomass~(kg~ha^-1)))+ #re-label x axis rather than leaving on log scale
  # scale_y_continuous(limits=c(0, 11), breaks=seq(0,10,2))+
    scale_x_continuous(labels = c(1, 10, 100), breaks = c(log(2),  log(11), log(101)))+ #because of +1 in log-transformation, here log(1) = 0*** and subtract 1 from all labels
  theme_bw()+
    guides(size = "none", colour = "none",  fill = guide_legend(title="Confidence level")) + 
    theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
    #            text = element_text(size = 24),
        legend.position='none')
leaf_part_plot

#raw effect size posterior distribution plot:
leaf_post_plot<-
sb_leaf_n15_brms %>%
  spread_draws(b_log_seabird_c) %>%
 # mutate(exp_b=exp(b_treatment_bNo_rats))%>%
  ggplot(aes(y = 0, x = b_log_seabird_c, fill = "#009E73")) +
  stat_halfeye(point_interval=median_hdi, .width=c(.95, .75), fatten_point = 2, slab_alpha = 0.6) +
  scale_fill_manual(values = alpha(c("#009E73"),0.3))+
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw() + 
  xlab("")+
  ylab("")+
 # scale_x_continuous(limits=c(-1.3, 2), breaks=seq(-1, 2,1))+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = "none",  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
      #  text=element_text(size=16,  family="sans"),
          axis.text.y = element_blank(),
        axis.ticks.y = element_blank())
leaf_post_plot



##make inset plots, then combine and save (w different colors)-------
leaf.plot.with.inset <-
  ggdraw() +
  draw_plot(leaf_part_plot) +
  draw_plot(leaf_post_plot, x = 0.1, y = .57, width = .4, height = .4)
leaf.plot.with.inset


turf.plot.with.inset <-
  ggdraw() +
  draw_plot(turf_part_plot) +
  draw_plot(turf_post_plot, x = 0.1, y = .57, width = .4, height = .4)
turf.plot.with.inset


figure2<-plot_grid(leaf.plot.with.inset, turf.plot.with.inset)
figure2

```



#model plots with size----
```{r}

#conditional effects, with partial residuals-----
#first for turf-----
#effect line:
me_turf_sb_size<-conditional_effects(sb_turf_n15_size_brms, prob = .75, effects = 'log_seabird_c', plot = FALSE)[[1]]

#extract partialized residuals
p_turf_sb_size<-partialize(sb_turf_n15_size_brms, vars= "log_seabird_c",  data = turf_n15_dat_wlog)

#get data for un-centering:
mean(turf_n15_dat_wlog$log_seabird, na.rm=TRUE) #3.218641

me_turf_seabird_unscale_size<-
  me_turf_sb_size%>%
  mutate(log_seabird = (log_seabird_c + 3.218641)) # + mean


#no jitter:
turf_part_plot_size<-
p_turf_sb_size %>%
  ggplot(aes(x = log_seabird, y = log_n15)) +
     geom_point(color = "#009E73", fill = "#009E73", alpha = 0.4, size = 3) + #, size = .8
    geom_ribbon(data = me_turf_seabird_unscale_size, aes(ymin = lower__, ymax=upper__), alpha = .2, fill = "#009E73")+
    geom_line(data = me_turf_seabird_unscale_size, aes(x = log_seabird, y = estimate__), lwd = 1.2, colour = "#009E73") +
  xlab(bquote(Seabird~biomass~(kg~ha^-1)))+ #re-label x axis rather than leaving on log scale
  ylab(expression(paste("Turf ", delta^15, "N"))) + 
  scale_x_continuous(labels = c(1, 10, 100), breaks = c(log(2),  log(11), log(101)))+ #because of +1 in log-transformation, here log(1) = 0*** and subtract 1 from all labels
    scale_y_continuous(labels = c(2, 4, 8), breaks = c(log(2), log(4), log(8)))+ #re-label y-axis. 
  theme_bw()+
    guides(size = "none", colour = "none",  fill = guide_legend(title="Confidence level")) + 
    theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
    #            text = element_text(size = 24),
        legend.position='none')
turf_part_plot_size


turf_part_plot_size_exp<-
p_turf_sb_size %>%
  ggplot(aes(x = log_seabird, y = exp(log_n15))) +
     geom_point(color = "#009E73", fill = "#009E73", alpha = 0.4, size = 3) + #, size = .8
    geom_ribbon(data = me_turf_seabird_unscale_size, aes(ymin = exp(lower__), ymax=exp(upper__)), alpha = .2, fill = "#009E73")+
    geom_line(data = me_turf_seabird_unscale_size, aes(x = log_seabird, y = exp(estimate__)), lwd = 1.2, colour = "#009E73") +
  xlab(bquote(Seabird~biomass~(kg~ha^-1)))+ #re-label x axis rather than leaving on log scale
  ylab(expression(paste("Turf ", delta^15, "N"))) + 
  scale_x_continuous(labels = c(1, 10, 100), breaks = c(log(2),  log(11), log(101)))+ #because of +1 in log-transformation, here log(1) = 0*** and subtract 1 from all labels
   # scale_y_continuous(labels = c(2, 4, 8), breaks = c(log(2), log(4), log(8)))+ #re-label y-axis. 
  theme_bw()+
    guides(size = "none", colour = "none",  fill = guide_legend(title="Confidence level")) + 
    theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
    #            text = element_text(size = 24),
        legend.position='none')
turf_part_plot_size_exp


#raw effect size posterior distribution plot:
turf_post_plot_size<-
sb_turf_n15_size_brms %>%
  spread_draws(b_log_seabird_c) %>%
 # mutate(exp_b=exp(b_treatment_bNo_rats))%>%
  ggplot(aes(y = 0, x = b_log_seabird_c, fill = "#009E73")) +
  stat_halfeye(point_interval=median_hdi, .width=c(.95, .75), fatten_point = 2, slab_alpha = 0.6) +
  scale_fill_manual(values = alpha(c("#009E73"),0.3))+
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw() + 
  xlab("")+
  ylab("")+
 # scale_x_continuous(limits=c(-1.3, 2), breaks=seq(-1, 2,1))+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = "none",  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
      #  text=element_text(size=16,  family="sans"),
          axis.text.y = element_blank(),
        axis.ticks.y = element_blank())
turf_post_plot_size


#now for leaves-----
#effect line:
me_leaf_sb_size<-conditional_effects(sb_leaf_n15_size_brms, prob = .75, effects = 'log_seabird_c', plot = FALSE)[[1]]

#extract partialized residuals
p_leaf_sb_size<-partialize(sb_leaf_n15_size_brms, vars= "log_seabird_c",  data = leaf_n15_dat_wlog)

#get data for un-scaling and centering:
mean(leaf_n15_dat_wlog$log_seabird, na.rm=TRUE) #3.125881

me_leaf_seabird_unscale_size<-
  me_leaf_sb_size%>%
  mutate(log_seabird = log_seabird_c + 3.125881 ) # + mean


leaf_part_plot_size<-
p_leaf_sb_size %>%
  ggplot(aes(x = log_seabird, y = log_n15)) +
     geom_point(color = "#009E73", fill = "#009E73", alpha = 0.4, size = 3) + #, size = .8
    geom_ribbon(data = me_leaf_seabird_unscale_size, aes(ymin = lower__, ymax=upper__), alpha = .2, fill = "#009E73")+
    geom_line(data = me_leaf_seabird_unscale_size, aes(x = log_seabird, y = estimate__), lwd = 1.2, colour = "#009E73") + 
 # xlab("Seabird biomass (log kg-1 ha-1)")+
ylab(expression(paste("Leaf ", delta^15, "N"))) + 
  xlab(bquote(Seabird~biomass~(kg~ha^-1)))+ #re-label x axis rather than leaving on log scale
    scale_y_continuous(labels = c(4, 8, 16), breaks = c(log(4),  log(8), log(16)))+ #re-label y-axis. 
    scale_x_continuous(labels = c(1, 10, 100), breaks = c(log(2),  log(11), log(101)))+ #because of +1 in log-transformation, here log(1) = 0*** and subtract 1 from all labels
  theme_bw()+
    guides(size = "none", colour = "none",  fill = guide_legend(title="Confidence level")) + 
    theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
    #            text = element_text(size = 24),
        legend.position='none')
leaf_part_plot_size


leaf_part_plot_size_exp<-
p_leaf_sb_size %>%
  ggplot(aes(x = log_seabird, y = exp(log_n15))) +
     geom_point(color = "#009E73", fill = "#009E73", alpha = 0.4, size = 3) + #, size = .8
    geom_ribbon(data = me_leaf_seabird_unscale_size, aes(ymin = exp(lower__), ymax=exp(upper__)), alpha = .2, fill = "#009E73")+
    geom_line(data = me_leaf_seabird_unscale_size, aes(x = log_seabird, y = exp(estimate__)), lwd = 1.2, colour = "#009E73") + 
 # xlab("Seabird biomass (log kg-1 ha-1)")+
ylab(expression(paste("Leaf ", delta^15, "N"))) + 
  xlab(bquote(Seabird~biomass~(kg~ha^-1)))+ #re-label x axis rather than leaving on log scale
 #   scale_y_continuous(labels = c(4, 8, 16), breaks = c(log(4),  log(8), log(16)))+ #re-label y-axis. 
    scale_x_continuous(labels = c(1, 10, 100), breaks = c(log(2),  log(11), log(101)))+ #because of +1 in log-transformation, here log(1) = 0*** and subtract 1 from all labels
  theme_bw()+
    guides(size = "none", colour = "none",  fill = guide_legend(title="Confidence level")) + 
    theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
    #            text = element_text(size = 24),
        legend.position='none')
leaf_part_plot_size_exp

#raw effect size posterior distribution plot:
leaf_post_plot_size<-
sb_leaf_n15_size_brms %>%
  spread_draws(b_log_seabird_c) %>%
 # mutate(exp_b=exp(b_treatment_bNo_rats))%>%
  ggplot(aes(y = 0, x = b_log_seabird_c, fill = "#009E73")) +
  stat_halfeye(point_interval=median_hdi, .width=c(.95, .75), fatten_point = 2, slab_alpha = 0.6) +
  scale_fill_manual(values = alpha(c("#009E73"),0.3))+
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw() + 
  xlab("")+
  ylab("")+
 # scale_x_continuous(limits=c(-1.3, 2), breaks=seq(-1, 2,1))+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = "none",  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
      #  text=element_text(size=16,  family="sans"),
          axis.text.y = element_blank(),
        axis.ticks.y = element_blank())
leaf_post_plot_size



##make inset plots, then combine and save (w different colors)-------
leaf.plot.with.inset_size <-
  ggdraw() +
  draw_plot(leaf_part_plot_size) +
  draw_plot(leaf_post_plot_size, x = 0.1, y = .57, width = .4, height = .4)
leaf.plot.with.inset_size

leaf.plot.with.inset_size_exp <-
  ggdraw() +
  draw_plot(leaf_part_plot_size_exp) +
  draw_plot(leaf_post_plot_size, x = 0.1, y = .57, width = .4, height = .4)
leaf.plot.with.inset_size_exp

turf.plot.with.inset_size <-
  ggdraw() +
  draw_plot(turf_part_plot_size) +
  draw_plot(turf_post_plot_size, x = 0.1, y = .57, width = .4, height = .4)
turf.plot.with.inset_size


turf.plot.with.inset_size_exp <-
  ggdraw() +
  draw_plot(turf_part_plot_size_exp) +
  draw_plot(turf_post_plot_size, x = 0.1, y = .57, width = .4, height = .4)
turf.plot.with.inset_size_exp

figure2_size<-plot_grid(leaf.plot.with.inset_size, turf.plot.with.inset_size)
figure2_size

figure2_size_exp<-plot_grid(leaf.plot.with.inset_size_exp, turf.plot.with.inset_size_exp)
figure2_size_exp

# Can save the plot with ggsave()
#ggsave(filename = "../outputs/figures/R/fig_2bc.png",        plot = figure2_size_exp,      width = 20,     height = 10,      units = "cm",     dpi = 300)

```


##re-plot for final figure (because alternative dag doesn't change this part) - with size
```{r}

turf_post_plot_alt_size<-
sb_turf_n15_size_brms %>%
  spread_draws(b_log_seabird_c) %>%
  ggplot(aes(y = 0, x = b_log_seabird_c, fill = after_stat(x < 0))) +
  stat_halfeye(point_interval=median_hdi, .width=c(.95, .75),  slab_alpha = 0.6, fatten_point=1) +
  scale_fill_manual(values = alpha(c("#d0e2af" ,"#e89c81"),1)) +#PNW color palette
  geom_vline(xintercept = 0, linetype = "dashed", lwd = .5) +
  theme_bw() + 
  xlab("")+
  ylab("")+
  #ggtitle("effect of seabird biomass on turf nutrients")+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = "none",  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
        text=element_text(size=10,  family="sans"),
          axis.text.y = element_blank(),
        axis.ticks.y = element_blank())
turf_post_plot_alt_size

#Save the plot with ggsave()
#ggsave(filename = "../outputs/figures/R/fig_6a.pdf", plot = turf_post_plot_alt_size,  width = 8,   height = 5,  units = "cm", dpi = 300)
```



#plot of seabird biomass
```{r}

#seabird data
sey_sb_dat<-read.csv("../data/seychelles_seabird_biomass.csv", stringsAsFactors = TRUE) 
str(sey_sb_dat)

sey_sb_dat_for_plot<-
  sey_sb_dat%>%
  mutate(Island_Site = 
           case_when(Island == "Aride" ~ "Aride",
                     Island == "Cousine" ~ "Cousine",
                     Island == "Felicite" ~ "Félicité",
                     Site == "High" ~ "Fregate NE",
                     Site == "Low" ~ "Fregate SW"))%>%
  mutate(rats = 
           case_when(Island == "Felicite" ~ "rats",
                     Island == "Fregate" ~ "rats eradicated",
                     Island == "Aride" ~ "never rats",
                     Island == "Cousine" ~ "never rats"))
sey_sb_dat_for_plot


##bubble plot by site-----
sey_sb_plot<-
sey_sb_dat_for_plot%>%
  mutate(round_seabird_biomass = round(seabird.biomass.total, digits = 0))%>%
  ggplot(aes(x =  reorder(Island_Site, seabird.biomass.total, mean), y = 0))+
  geom_point(aes(fill = rats,  colour = rats, size = seabird.biomass.total), alpha = .8)+
  geom_text(aes(label = round_seabird_biomass))+ #, vjust = -2
        scale_fill_manual(name = "", values = c("#FC8D62", "#8DA0CB", "#E78AC3"), breaks = c("rats", "rats eradicated", "never rats"), guide = "none")+
      scale_colour_manual(name = "", values = c("#FC8D62", "#8DA0CB", "#E78AC3"), breaks = c("rats", "rats eradicated", "never rats"))+  
   scale_size_continuous(range = c(2,15), breaks = c(0, 50, 150), name = "seabird biomass", guide = "none")+
  xlab("")+
  ylab(bquote(Seabird~biomass~(kg~ha^-1)))+
  theme() +
theme(axis.title.y =element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y=element_blank(),
    axis.line = element_blank(),
    legend.direction = "horizontal",
    legend.position = c(.5,.9),
    text=element_text(size=12,  family="sans"),
    legend.key=element_blank())
sey_sb_plot


#ggsave(filename = "../outputs/figures/R/fig_2a.jpg",       plot = sey_sb_plot,     width = 10,        height = 4,     units = "cm",      dpi = 300)


```