---
title: "Turf nutrients vs turf productivity"
author: "CEB"
date: '2024-09-04'
output: html_document
---

#load packages
```{r}
#for everything:
library(tidyverse)

#for bayesian analysis:
library(brms)
library(tidybayes)

#for partialize:
library(jtools)

#for combining plots:
library(cowplot)

```


###set plot theme
```{r}
theme_casey<-
  theme_bw()+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        text = element_text(size = 14, family = "Arial"),
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA)
        )

theme_set(theme_casey) 
  
```


#load  data 
```{r}

turf_pp_cage_all_dat<- read.csv("../data/seychelles_turf_pp_by_cage_dat.csv") #from data prep file

```


##Bayesian analysis based on DAGs - Hypothesis 3: effect of turf nutrients on turf growth
```{r}
#total effect = control for exposure (all other variables controlled for)
#direct effect = control for exposure and turf height

#add column for scaled data:----
turf_pp_cage_all_dat_c<-
  turf_pp_cage_all_dat%>%
  mutate(turf_n15_c = base::scale(Turf_N15, center = TRUE, scale = FALSE),
         exposure_c = base::scale(Exposure_J_m3, center = TRUE, scale = FALSE),
         turf_height_c = base::scale(Average_turf_height_initial, center = TRUE, scale = FALSE))
turf_pp_cage_all_dat_c

#brms models------

#linear model, uninformative prior, direct path:
turf_pp_nutrients_direct_brms<-
  brm(
 Turf_growth_mm_per_day~turf_n15_c + exposure_c + turf_height_c + (1|Island),
  data = turf_pp_cage_all_dat_c, 
  iter = 3000, warmup = 1000, chains = 4, cores = 4,
   control = list(adapt_delta = 0.999, max_treedepth = 15), 
      file = "../outputs/brms/turf_pp_nutrients_direct_brms") #all good
print(turf_pp_nutrients_direct_brms) #all good

pp_check(turf_pp_nutrients_direct_brms) #looks good
plot(turf_pp_nutrients_direct_brms, ask = FALSE) #looks good

hypothesis(turf_pp_nutrients_direct_brms, "turf_n15_c>0") 
#hypothesis              est      error     lower     upper       evidence ratio        posterior probability
#(turf_n15_c) > 0       0.04	    0.03	    0	        0.09	        15.56               	0.94	


#extract some values:------
turf_pp_nutrients_direct_brms %>%
  spread_draws(b_turf_n15_c) %>%
  median_hdi(b_turf_n15_c)
#b_log_seabird      lower       upper       width   point     interval
# 0.04444214    	-0.01229976   0.09944944			  0.95	median	hdi
#so for each one unit increase in turf n15, turf growth increases by 0.04 mm/day


#linear model, uninformative prior, total effect:
turf_pp_nutrients_total_brms<-
  brm(
 Turf_growth_mm_per_day~turf_n15_c + exposure_c  + (1|Island),
  data = turf_pp_cage_all_dat_c, 
  iter = 3000, warmup = 1000, chains = 4, cores = 4,
   control = list(adapt_delta = 0.999, max_treedepth = 15), 
      file = "../outputs/brms/turf_pp_nutrients_total_brms") #all good
print(turf_pp_nutrients_total_brms) #all good

pp_check(turf_pp_nutrients_total_brms) #looks good
plot(turf_pp_nutrients_total_brms, ask = FALSE) #looks good

hypothesis(turf_pp_nutrients_total_brms, "turf_n15_c>0") 
#hypothesis              est      error     lower     upper       evidence ratio        posterior probability
#(turf_n15_c) > 0       0.05      	0.03    	0.01    	0.1	        31.92	                0.97	*


#extract some values:------
turf_pp_nutrients_total_brms %>%
  spread_draws(b_turf_n15_c) %>%
  median_hdi(b_turf_n15_c)
#b_log_seabird      lower       upper       width   point     interval
# 0.05428809	-0.0006076354	0.1118286	    0.95    	median	hdi
#so for each one unit increase in turf n15, turf growth increases by 0.05 mm/day



#note: results are nearly identical to original model without exposure, and to models with exposure only (based on DAG without link from prior herbivory to N15) - findings robust to DAG decisions.
#no need for priors - sampling working well

```

##plot it (total effect)-----
```{r}
#plot partialized residuals-----
me_n15<-conditional_effects(turf_pp_nutrients_total_brms, prob = .75, effects = 'turf_n15_c', plot = FALSE)[[1]]

#extract partialized residuals
p_n15<-partialize(turf_pp_nutrients_total_brms, vars= "turf_n15_c",  data = turf_pp_cage_all_dat_c)


#get data for un-centering:
mean(turf_pp_cage_all_dat_c$Turf_N15, na.rm=TRUE) #4.67381

me_turf_n15_pp_unscale<-
  me_n15%>%
  mutate(Turf_N15 = (turf_n15_c  + 4.67381 )) #+ mean



##correct colour plots - combine and save-----
turf_pp_post_plot<-
turf_pp_nutrients_total_brms %>%
  spread_draws(b_turf_n15_c) %>%
  ggplot(aes(y = 0, x = b_turf_n15_c, fill = "#EE7733")) +
  stat_halfeye(point_interval=median_hdi, .width=c(.95, .75), fatten_point = 2, slab_alpha = 0.6) +
  scale_fill_manual(values = alpha(c("#EE7733"),0.3))+
  geom_vline(xintercept = 0, linetype = "dashed") +
    scale_x_continuous(breaks = c(0.0, 0.1))+
  theme_bw() + 
  xlab("")+
  ylab("")+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = "none",  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
       # text=element_text(size=16,  family="sans"),
          axis.text.y = element_blank(),
        axis.ticks.y = element_blank())
turf_pp_post_plot



turf_pp_n15_part_plot<-
p_n15 %>%
  ggplot(aes(x = Turf_N15, y = Turf_growth_mm_per_day)) +
     #  geom_jitter(color = "#EE7733", fill = "#EE7733", alpha = 0.4, size = 3, width=.05, height = 0) + #, size = .8  
     geom_point(color = "#EE7733", fill = "#EE7733", alpha = 0.4, size = 3) + #, size = .8  width=.07, height = 0,
    geom_ribbon(data = me_turf_n15_pp_unscale, aes(ymin = lower__, ymax=upper__), alpha = .2, fill = "#EE7733")+
    geom_line(data = me_turf_n15_pp_unscale, aes(x = Turf_N15, y = estimate__), lwd = 1.2, colour = "#EE7733") + ##scale line thickness to PP - >0.9 = 1.2 (original thickness)
xlab(expression(paste("Turf ", delta^15, "N"))) + 
  ylab(bquote(Turf~productivity~(mm~day^-1)))+
  theme_bw()+
    guides(size = "none", colour = "none",  fill = guide_legend(title="Confidence level")) + 
    theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(),
    #            text = element_text(size = 24),
        legend.position='none')
turf_pp_n15_part_plot

##combine and save---------
##make inset plots, then combine and save:
turf.pp.n15.plot.with.inset <-
  ggdraw() +
  draw_plot(turf_pp_n15_part_plot) +
  draw_plot(turf_pp_post_plot, x = 0.1, y = .64, width = .35, height = .35)
turf.pp.n15.plot.with.inset


# Can save the plot with ggsave()
#ggsave(filename = "../outputs/figures/R/fig_3a.png",      plot = turf.pp.n15.plot.with.inset,  width = 11,       height = 7.5,   units = "cm",     dpi = 300)


```


#also look at proportional growth to make sure this n15 effect isn't driven by initial turf height:
```{r}
turf_pp_cage_all_dat_prop<-
  turf_pp_cage_all_dat%>%
  mutate( Prop_turf_growth_day = Turf_growth_mm_per_day/Average_turf_height_initial) #decided to use growth per day, based on previous turf PP studies, but here compared to account for turf height
turf_pp_cage_all_dat


#report initial heights in manuscript:----
turf_pp_cage_all_dat_prop%>%
  group_by(Island, Site)%>%
  summarize(mean_initial_height = mean(Average_turf_height_initial))

turf_pp_cage_all_dat_prop%>%
  group_by(Island, Site)%>%
  summarize(min_init_height = min(Average_turf_height_initial),
            max_init_height = max(Average_turf_height_initial))


#bayesian model for prop growth-----
#don't need initial height in these models - already accounted for in response (so just look at total effect):
#add column for scaled data:----
turf_pp_cage_all_dat_prop_c<-
  turf_pp_cage_all_dat_prop%>%
  mutate(turf_n15_c = base::scale(Turf_N15, center = TRUE, scale = FALSE),
         exposure_c = base::scale(Exposure_J_m3, center = TRUE, scale = FALSE))
turf_pp_cage_all_dat_prop_c

#brms models------

#linear model, uninformative prior: 
prop_turf_pp_nutrients_brms<-
  brm(
 Prop_turf_growth_day~turf_n15_c + exposure_c + (1|Island),
  data = turf_pp_cage_all_dat_prop_c, 
  iter = 3000, warmup = 1000, chains = 4, cores = 4,
   control = list(adapt_delta = 0.999, max_treedepth = 15), 
      file = "../outputs/brms/prop_turf_pp_nutrients_brms") #all good
print(prop_turf_pp_nutrients_brms) #all good

pp_check(prop_turf_pp_nutrients_brms) #looks good
plot(prop_turf_pp_nutrients_brms, ask = FALSE) #looks good

hypothesis(prop_turf_pp_nutrients_brms, "turf_n15_c>0") 
#hypothesis              est      error     lower     upper       evidence ratio        posterior probability
# (turf_n15_c) > 0        0.03	     0.02	    0.01	0.06	          42.48                 	0.98	*
#nearly identical to raw data model


#extract some values:------
prop_turf_pp_nutrients_brms %>%
  spread_draws(b_turf_n15_c) %>%
  median_hdci(b_turf_n15_c)
#b_log_seabird      lower       upper       width   point     interval
#0.03389067 	0.0002087316	0.06611143				  0.95	median	hdi
#.03 increase in proportional growth



```



##re-plot for alternative dag figure (because changing dag doesn't change this part)
```{r}

turf_pp_post_plot_alt<-
turf_pp_nutrients_total_brms %>%
  spread_draws(b_turf_n15_c) %>%
  ggplot(aes(y = 0, x = b_turf_n15_c, fill = after_stat(x < 0))) +
  stat_halfeye(point_interval=median_hdi, .width=c(.95, .75), fatten_point = 1, slab_alpha = 0.6) +
  scale_fill_manual(values = alpha(c("#d0e2af" ,"#e89c81"),1)) +#PNW color palette
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw() + 
  xlab("")+
  ylab("")+
  #ggtitle("effect of turf nutrients on turf productivity")+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = "none",  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
        text=element_text(size=10,  family="sans"),
          axis.text.y = element_blank(),
        axis.ticks.y = element_blank())
turf_pp_post_plot_alt

#Save the plot with ggsave()
#ggsave(filename = "../outputs/figures/R/fig_6b.pdf", plot = turf_pp_post_plot_alt,  width = 8,   height = 5,  units = "cm", dpi = 300)
```


