---
title: "wind roses"
author: "CEB"
date: '2025-03-04'
output: html_document
---


#load packages
```{r}
library(tidyverse)
```



#load full wind data - from Seychelles Meterological Org
```{r}

dir_dat<-read.csv("../data/SEYCHELLES AIRPORT_hrly_wind_dir_2012_2022.csv")
#NOTE: Data from 1st Jan 2012 to 31st December 2017 are from manned station and from 1st January 2018 to 31st Dec 2022 from AWOS 

speed_dat<-read.csv("../data/SEYCHELLES AIRPORT_hrly_wind_speed_2012_2022.csv")
#note: unit = KNOTS


#make long:
dir_dat_long<-
  dir_dat%>%
  pivot_longer(names_to = "hour", cols = c(X0:X23), values_to = "direction")
dir_dat_long

speed_dat_long<-
  speed_dat%>%
  pivot_longer(names_to = "hour", cols = c(X0:X23), values_to = "speed_knots")
speed_dat_long


#combine:
wind_dat_long<-
  full_join(dir_dat_long, speed_dat_long)%>%
  mutate(speed_ms = speed_knots/1.94384)
wind_dat_long
#perfect!

range(wind_dat_long$speed_ms, na.rm = TRUE)
range(wind_dat_long$speed_knots, na.rm = TRUE)


```


#Load function for plotting windrose:
```{r}
##Function Written By Andy Clifton : https://stackoverflow.com/users/2514568/andy-clifton##
#For detailsl go here: https://stackoverflow.com/questions/17266780/wind-rose-with-ggplot-r/17266781#17266781

require(ggplot2)
require(RColorBrewer)

plot.windrose <- function(data,
                          spd,
                          dir,
                          spdres = 2,
                          dirres = 30,
                          spdmin = 2,
                          spdmax = 20,
                          spdseq = NULL,
                          palette = "YlGnBu",
                          countmax = NA,
                          debug = 0){
  
  
  # Look to see what data was passed in to the function
  if (is.numeric(spd) & is.numeric(dir)){
    # assume that we've been given vectors of the speed and direction vectors
    data <- data.frame(spd = spd,
                       dir = dir)
    spd = "spd"
    dir = "dir"
  } else if (exists("data")){
    # Assume that we've been given a data frame, and the name of the speed 
    # and direction columns. This is the format we want for later use.    
  }  
  
  # Tidy up input data ----
  n.in <- NROW(data)
  dnu <- (is.na(data[[spd]]) | is.na(data[[dir]]))
  data[[spd]][dnu] <- NA
  data[[dir]][dnu] <- NA
  
  # figure out the wind speed bins ----
  if (missing(spdseq)){
    spdseq <- seq(spdmin,spdmax,spdres)
  } else {
    if (debug >0){
      cat("Using custom speed bins \n")
    }
  }
  # get some information about the number of bins, etc.
  n.spd.seq <- length(spdseq)
  n.colors.in.range <- n.spd.seq - 1
  
  # create the color map
  spd.colors <- colorRampPalette(brewer.pal(min(max(3,
                                                    n.colors.in.range),
                                                min(9,
                                                    n.colors.in.range)),                                               
                                            palette))(n.colors.in.range)
  
  if (max(data[[spd]],na.rm = TRUE) > spdmax){    
    spd.breaks <- c(spdseq,
                    max(data[[spd]],na.rm = TRUE))
    spd.labels <- c(paste(c(spdseq[1:n.spd.seq-1]),
                          '-',
                          c(spdseq[2:n.spd.seq])),
                    paste(spdmax,
                          "-",
                          max(data[[spd]],na.rm = TRUE)))
    spd.colors <- c(spd.colors, "grey50")
  } else{
    spd.breaks <- spdseq
    spd.labels <- paste(c(spdseq[1:n.spd.seq-1]),
                        '-',
                        c(spdseq[2:n.spd.seq]))    
  }
  data$spd.binned <- cut(x = data[[spd]],
                         breaks = spd.breaks,
                         labels = spd.labels,
                         ordered_result = TRUE)
  # clean up the data
  data <- na.omit(data)
  
  # figure out the wind direction bins
  dir.breaks <- c(-dirres/2,
                  seq(dirres/2, 360-dirres/2, by = dirres),
                  360+dirres/2)  
  dir.labels <- c(paste(360-dirres/2,"-",dirres/2),
                  paste(seq(dirres/2, 360-3*dirres/2, by = dirres),
                        "-",
                        seq(3*dirres/2, 360-dirres/2, by = dirres)),
                  paste(360-dirres/2,"-",dirres/2))
  # assign each wind direction to a bin
  dir.binned <- cut(data[[dir]],
                    breaks = dir.breaks,
                    ordered_result = TRUE)
  levels(dir.binned) <- dir.labels
  data$dir.binned <- dir.binned
  
  # Run debug if required ----
  if (debug>0){    
    cat(dir.breaks,"\n")
    cat(dir.labels,"\n")
    cat(levels(dir.binned),"\n")       
  }  
  
  # deal with change in ordering introduced somewhere around version 2.2
  if(packageVersion("ggplot2") > "2.2"){    
    cat("Hadley broke my code\n")
    data$spd.binned = with(data, factor(spd.binned, levels = rev(levels(spd.binned))))
    spd.colors = rev(spd.colors)
  }
  
  # create the plot ----
  p.windrose <- ggplot(data = data,
                       aes(x = dir.binned,
                           fill = spd.binned)) +
    geom_bar() + 
    scale_x_discrete(drop = FALSE,
                     labels = waiver()) +
    coord_polar(start = -((dirres/2)/360) * 2*pi) +
    scale_fill_manual(name = "Wind Speed (m/s)", 
                      values = spd.colors,
                      drop = FALSE) +
    theme(axis.title.x = element_blank())
  
  # adjust axes if required
  if (!is.na(countmax)){
    p.windrose <- p.windrose +
      ylim(c(0,countmax))
  }
  
  # print the plot
  print(p.windrose)  
  
  # return the handle to the wind rose
  return(p.windrose)
}

```


##now use function to plot windrose:
```{r}
#get range of values to plot appropriate scale: 
range(wind_dat_long[wind_dat_long$yyyy == 2022,]$speed_ms, na.rm = TRUE) #0, 9.77

#make new labels for facets:
month_labels <- c("1" = "Jan", "2" =  "Feb", "3" =  "Mar", "4" = "Apr", "5" =  "May", "6" ="Jun",
                  "7" ="Jul","8" = "Aug", "9" ="Sep", "10" ="Oct","11" = "Nov", "12" ="Dec")

degree_labels <- c("N", "", "",  "E",   "", "", "S",   "", "", "W" ,"", ""  )


wind_rose_plot<-
wind_dat_long%>%
    filter(yyyy == 2022)%>%
  plot.windrose(spd = "speed_ms",
                        dir = "direction",
                        spdmax = 10,
                  spdseq = c(0,2, 4, 6, 8, 10))+  #
  facet_wrap(~mm,  ncol = 3, labeller = labeller(mm = month_labels))+
  guides(fill = guide_legend(reverse = TRUE))+ #reverse direction of legend because when put on bottom it puts higher wind speeds first. 
  theme_bw()+
    xlab("")+
  ylab("Number of observations")+
    scale_x_discrete(drop = FALSE,  labels = degree_labels) + #change degree labels to N,E,S,W
#  ggtitle("2022 wind speed and direction by month")+ #don't need title
  theme(#axis.text.x = element_blank(),axis.title.x = element_blank(),#removes degree labels. or can just adjust them probably. 
       axis.text.y = element_text(size = 10, face = "plain"), #remove count labels
        axis.ticks = element_blank(), #remove y axis ticks 
        panel.grid.major = element_line(color = rgb(0.9, 0.9, 0.9, 0.5), linewidth = 0.25),   # Thinner lines
        panel.grid.minor = element_line(color = rgb(0.9, 0.9, 0.9, 0.5), linewidth = 0.25), 
 strip.background = element_rect(fill = "transparent",  # No fill
                                   color = "black",        # Black border
                                   linewidth = 0.5),        # Border thickness
 legend.position = "bottom") #put axis at bottom


wind_rose_plot


#ggsave(filename = "../outputs/figures/wind_rose_plot.png",  plot = wind_rose_plot, width = 6,  height = 8,units = "in",dpi = 300)


```



